torso_params: 
  length: 0.55
  width: 0.25
  height: 0.2
  mass: 36
  start_pos: [0, 0, 0.5]

head_params:
  length: 0.2
  width: 0.25
  height: 0.2
  mass: 15
  offset: [0.05, 0, 0]

thigh_params: 
  length: 0.25
  width: 0.08
  mass: 3
  torso_offset: [-0.13, 0.00, 0]
  head_offset: [0, 0.0, 0]

shin_params: 
  length: 0.3
  width: 0.08
  mass: 2
  offset: [0, 0.0, 0]

wheel_params:
  radius: 0.12
  width: 0.1
  mass: 2
  offset: [0, 0.00, 0]
  friction: [0.9, 0.5, 0.05]
  solref: [0.1, 0.1]
